In [41]:
import pandas as pd
import scipy.stats as st
import statsmodels.api as sm
import statsmodels.formula.api as smf
from matplotlib import pyplot as plt
import seaborn as sns
from linearmodels import PanelOLS

In [2]:
data = pd.read_csv('/Users/afifmazhar/Desktop/Data Science/Data Science Projects/Econometrics/Gini Index/data/final_data.csv', header = 0)
data.drop('Unnamed: 0', axis = 1, inplace=True)

In [3]:
data.head()

,Country,Country_code,Year,Gini,real_GDP,cpi,ip,unrate
0,Australia,AUS,1993-01-01,33.95,221619.25,1.753839,56.460825,10.880851
1,Australia,AUS,1994-01-01,33.95,232355.75,1.968183,59.257840,9.713438
2,Australia,AUS,1995-01-01,32.60,239223.25,4.623810,60.950436,8.471992
3,Australia,AUS,1996-01-01,33.95,248867.00,2.626375,63.428274,8.513908
4,Australia,AUS,1997-01-01,33.95,260326.25,0.228107,64.264320,8.362599

In [4]:
unit_col_name='Country'
time_period_col_name='Year'
 
#Create the dummy variables, one for each country
data_dummies = pd.get_dummies(data[unit_col_name])

In [6]:
data_w_dummies = data.join(data_dummies)

In [36]:
data_w_dummies.head()

,Country,Country_code,Year,Gini,real_GDP,cpi,ip,unrate,Australia,Germany,Spain,Sweden,United Kingdom,United States
0,Australia,AUS,1993-01-01,33.95,221619.25,1.753839,56.460825,10.880851,1,0,0,0,0,0
1,Australia,AUS,1994-01-01,33.95,232355.75,1.968183,59.257840,9.713438,1,0,0,0,0,0
2,Australia,AUS,1995-01-01,32.60,239223.25,4.623810,60.950436,8.471992,1,0,0,0,0,0
3,Australia,AUS,1996-01-01,33.95,248867.00,2.626375,63.428274,8.513908,1,0,0,0,0,0
4,Australia,AUS,1997-01-01,33.95,260326.25,0.228107,64.264320,8.362599,1,0,0,0,0,0

In [45]:
y = 'Gini'
X = ['real_GDP','cpi','ip','unrate']
unit_names = ['Australia', 'Sweden', 'Germany', 'Spain', 'United Kingdom', 'United States']
exog_X = sm.add_constant(data[X])
exog_X

     const      real_GDP       cpi          ip     unrate
0      1.0  221619.25000  1.753839   56.460825  10.880851
1      1.0  232355.75000  1.968183   59.257840   9.713438
2      1.0  239223.25000  4.623810   60.950436   8.471992
3      1.0  248867.00000  2.626375   63.428274   8.513908
4      1.0  260326.25000  0.228107   64.264320   8.362599
..     ...           ...       ...         ...        ...
157    1.0   17390.29525  0.061153  100.848683   5.275000
158    1.0   17680.27375  0.171469   98.656633   4.875000
159    1.0   18076.65150  0.174316  100.000000   4.358333
160    1.0   18609.07825  0.158166  103.180917   3.891667
161    1.0   19036.05225  0.188682  102.488542   3.683333

[162 rows x 5 columns]

In [31]:
lsdv_expr = y + ' ~ '
i = 0
for X_var_name in X:
    if i > 0:
        lsdv_expr = lsdv_expr + ' + ' + X_var_name
    else:
        lsdv_expr = lsdv_expr + X_var_name
    i = i + 1
for dummy_name in unit_names[:-1]:
    lsdv_expr = lsdv_expr + ' + ' + dummy_name
 
print('Regression expression for OLS with dummies = ' + lsdv_expr)

Regression expression for OLS with dummies = Gini ~ real_GDP + cpi + ip + unrate + Australia + Sweden + Germany + Spain + United Kingdom

In [50]:
mod = PanelOLS(data.Gini, exog_X, entity_effects = True)

re_res = mod.fit()

print(re_res)

ValueError: Series can only be used with a 2-level MultiIndex

In [43]:
lsdv_model = smf.ols('Gini ~ real_GDP + cpi + ip + unrate + Australia + Sweden + Germany + Spain + United Kingdom', data_w_dummies)
#lsdv_model_results = lsdv_model.fit()
#print(lsdv_model_results.summary())

SyntaxError: invalid syntax (<unknown>, line 1)